// <auto-generated />
namespace Your_IoT_Handprint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class userIdToEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userIdToEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "202008161316351_userIdToEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
